export const TOKENS = {
  apiClient: Symbol("apiClient"),
  createCustomerUseCase: Symbol("createCustomerUseCase"),
  createProductUseCase: Symbol("createProductUseCase"),
  createSupplierUseCase: Symbol("createSupplierUseCase"),
  customerRepository: Symbol("customerRepository"),
  deactivateCustomerUseCase: Symbol("deactivateCustomerUseCase"),
  deactivateProductUseCase: Symbol("deactivateProductUseCase"),
  deactivateSupplierUseCase: Symbol("deactivateSupplierUseCase"),
  eventBus: Symbol("eventBus"),
  getSystemHealthUseCase: Symbol("getSystemHealthUseCase"),
  healthRepository: Symbol("healthRepository"),
  listCustomersUseCase: Symbol("listCustomersUseCase"),
  listProductsUseCase: Symbol("listProductsUseCase"),
  listSuppliersUseCase: Symbol("listSuppliersUseCase"),
  productRepository: Symbol("productRepository"),
  storage: Symbol("storage"),
  supplierRepository: Symbol("supplierRepository"),
  updateCustomerUseCase: Symbol("updateCustomerUseCase"),
  updateProductUseCase: Symbol("updateProductUseCase"),
  updateSupplierUseCase: Symbol("updateSupplierUseCase"),
} as const;
