export const TOKENS = {
  apiClient: Symbol("apiClient"),
  cancelCashEntryUseCase: Symbol("cancelCashEntryUseCase"),
  cancelCustomerInteractionUseCase: Symbol("cancelCustomerInteractionUseCase"),
  cancelProductionOrderUseCase: Symbol("cancelProductionOrderUseCase"),
  cancelPurchaseUseCase: Symbol("cancelPurchaseUseCase"),
  cancelSaleUseCase: Symbol("cancelSaleUseCase"),
  completeCustomerInteractionUseCase: Symbol(
    "completeCustomerInteractionUseCase",
  ),
  createCustomerUseCase: Symbol("createCustomerUseCase"),
  createProductUseCase: Symbol("createProductUseCase"),
  createProductionOrderUseCase: Symbol("createProductionOrderUseCase"),
  createPurchaseUseCase: Symbol("createPurchaseUseCase"),
  createRecipeUseCase: Symbol("createRecipeUseCase"),
  createSaleUseCase: Symbol("createSaleUseCase"),
  createSupplierUseCase: Symbol("createSupplierUseCase"),
  customerRepository: Symbol("customerRepository"),
  customerRelationshipRepository: Symbol("customerRelationshipRepository"),
  deactivateCustomerUseCase: Symbol("deactivateCustomerUseCase"),
  deactivateProductUseCase: Symbol("deactivateProductUseCase"),
  deactivateSupplierUseCase: Symbol("deactivateSupplierUseCase"),
  eventBus: Symbol("eventBus"),
  cashFlowRepository: Symbol("cashFlowRepository"),
  getCashFlowSummaryUseCase: Symbol("getCashFlowSummaryUseCase"),
  getBusinessDashboardUseCase: Symbol("getBusinessDashboardUseCase"),
  getBusinessReportsUseCase: Symbol("getBusinessReportsUseCase"),
  getCustomerRelationshipSummaryUseCase: Symbol(
    "getCustomerRelationshipSummaryUseCase",
  ),
  getSystemHealthUseCase: Symbol("getSystemHealthUseCase"),
  healthRepository: Symbol("healthRepository"),
  inventoryRepository: Symbol("inventoryRepository"),
  listCustomersUseCase: Symbol("listCustomersUseCase"),
  listCashEntriesUseCase: Symbol("listCashEntriesUseCase"),
  listCustomerInteractionsUseCase: Symbol("listCustomerInteractionsUseCase"),
  listInventoryBalancesUseCase: Symbol("listInventoryBalancesUseCase"),
  listProductsUseCase: Symbol("listProductsUseCase"),
  listProductionOrdersUseCase: Symbol("listProductionOrdersUseCase"),
  listPurchasesUseCase: Symbol("listPurchasesUseCase"),
  listRecipesUseCase: Symbol("listRecipesUseCase"),
  listSalesUseCase: Symbol("listSalesUseCase"),
  listStockMovementsUseCase: Symbol("listStockMovementsUseCase"),
  listSuppliersUseCase: Symbol("listSuppliersUseCase"),
  productRepository: Symbol("productRepository"),
  productionInventoryGateway: Symbol("productionInventoryGateway"),
  productionOrderRepository: Symbol("productionOrderRepository"),
  purchaseInventoryGateway: Symbol("purchaseInventoryGateway"),
  purchaseFinanceGateway: Symbol("purchaseFinanceGateway"),
  purchaseRepository: Symbol("purchaseRepository"),
  receivePurchaseUseCase: Symbol("receivePurchaseUseCase"),
  recipeRepository: Symbol("recipeRepository"),
  registerCashEntryUseCase: Symbol("registerCashEntryUseCase"),
  registerCustomerInteractionUseCase: Symbol(
    "registerCustomerInteractionUseCase",
  ),
  registerInventoryAdjustmentUseCase: Symbol("registerInventoryAdjustmentUseCase"),
  registerLossUseCase: Symbol("registerLossUseCase"),
  settleCashEntryUseCase: Symbol("settleCashEntryUseCase"),
  finishProductionOrderUseCase: Symbol("finishProductionOrderUseCase"),
  paySaleUseCase: Symbol("paySaleUseCase"),
  saleFinanceGateway: Symbol("saleFinanceGateway"),
  saleInventoryGateway: Symbol("saleInventoryGateway"),
  saleRepository: Symbol("saleRepository"),
  storage: Symbol("storage"),
  startProductionOrderUseCase: Symbol("startProductionOrderUseCase"),
  supplierRepository: Symbol("supplierRepository"),
  updateCustomerUseCase: Symbol("updateCustomerUseCase"),
  updateProductUseCase: Symbol("updateProductUseCase"),
  updateSupplierUseCase: Symbol("updateSupplierUseCase"),
} as const;
