export const TOKENS = {
  apiClient: Symbol("apiClient"),
  authRepository: Symbol("authRepository"),
  auditLogRepository: Symbol("auditLogRepository"),
  cashFlowRepository: Symbol("cashFlowRepository"),
  eventBus: Symbol("eventBus"),
  getBusinessDashboardUseCase: Symbol("getBusinessDashboardUseCase"),
  getSystemHealthUseCase: Symbol("getSystemHealthUseCase"),
  healthRepository: Symbol("healthRepository"),
  inventoryRepository: Symbol("inventoryRepository"),
  listAuditLogsUseCase: Symbol("listAuditLogsUseCase"),
  listCashEntriesUseCase: Symbol("listCashEntriesUseCase"),
  listInventoryBalancesUseCase: Symbol("listInventoryBalancesUseCase"),
  listProductionOrdersUseCase: Symbol("listProductionOrdersUseCase"),
  listProductsUseCase: Symbol("listProductsUseCase"),
  listSalesUseCase: Symbol("listSalesUseCase"),
  mobileOperationsRepository: Symbol("mobileOperationsRepository"),
  productRepository: Symbol("productRepository"),
  productionOrderRepository: Symbol("productionOrderRepository"),
  purchaseRepository: Symbol("purchaseRepository"),
  saleRepository: Symbol("saleRepository"),
  storage: Symbol("storage"),
} as const;
